[package]
name = "digipin"
version = "0.1.0-alpha.4"
edition = "2024"
license = "Apache-2.0"
description = "Rust library for encoding and decoding DIGIPIN (Digital Postal Index Number)"
keywords = ["digipin", "geocoding", "postal", "spatial", "gis", "address", "india"]
repository = "https://github.com/pranamphd/digipin"

[dependencies]
